on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ./tests

    - name: Compile main
      run: g++ -std=c++20 directory_and_file.cpp -o directory_and_file
      
    - name: Run main
      run: ./directory_and_file

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: directory_and_file
        path: build
